# Generated by Django 5.2.4 on 2025-07-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
